import axios from "axios";
import { api_url } from "../../../../request/APIRequestURL";

export function getWorkSched(data){
    return axios.request({
        method:'POST',
        data:data,
        url:'api/DTR/getWorkSched'
    })
}
export function getEmpDTRV2(data){
    return axios.request({
        method:'POST',
        data:data,
        url:'api/DTR/getEmpDTRV2'
    })
}
export function getEmpRawLogs(data){
    return axios.request({
        method:'POST',
        data:data,
        url:'api/DTR/getEmpRawLogs'
    })
}
export function getLeaveDays(data){
    return axios.request({
        method:'POST',
        data:data,
        url:'api/DTR/getLeaveDays'
    })
}
export function getAllHolidays(data){
    return axios.request({
        method:'GET',
        data:data,
        url:'api/leaveapplication/getAllHolidays'
    })
}
export function getEmpOBOFT(data){
    return axios.request({
        method:'POST',
        data:data,
        url:'api/DTR/getEmpOBOFT'
    })
}
export function getEmpRectification(data){
    return axios.request({
        method:'POST',
        data:data,
        url:'api/DTR/getEmpRectification'
    })
}
export function tempHolidays(){
    return {data:
        {
            response:
        [
        {
            "holiday_date1": "2023-01-01",
            "holiday_desc": "New Year",
            "holiday_type": 1,
            "holiday_date2": "2023-01-01",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2023-01-01",
            "holiday_desc": "NEW YEAR'S DAY",
            "holiday_type": 1,
            "holiday_date2": "2023-01-01",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2023-01-02",
            "holiday_desc": "Special Non Working",
            "holiday_type": 3,
            "holiday_date2": "2023-01-02",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2023-02-24",
            "holiday_desc": "PROCLAMATION NO. 167 EDSA PEOPLE POWER",
            "holiday_type": 3,
            "holiday_date2": "2023-02-24",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2023-04-05",
            "holiday_desc": "OPMC 16-2023",
            "holiday_type": 7,
            "holiday_date2": "2023-04-05",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2023-04-06",
            "holiday_desc": "Maundy Thursday",
            "holiday_type": 1,
            "holiday_date2": "2023-04-06",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2023-04-07",
            "holiday_desc": "Good Friday",
            "holiday_type": 1,
            "holiday_date2": "2023-04-07",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2023-04-10",
            "holiday_desc": "Araw ng Kagitingan",
            "holiday_type": 1,
            "holiday_date2": "2023-04-10",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2023-04-21",
            "holiday_desc": "Eid'l Fitr",
            "holiday_type": 1,
            "holiday_date2": "2023-04-21",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2023-05-01",
            "holiday_desc": "Labor Day",
            "holiday_type": 1,
            "holiday_date2": "2023-05-01",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2023-05-19",
            "holiday_desc": "BALANGAY FESTIVAL",
            "holiday_type": 3,
            "holiday_date2": "2023-05-19",
            "holiday_cover": 2,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2023-06-12",
            "holiday_desc": "Philippine Independence Day",
            "holiday_type": 1,
            "holiday_date2": "2023-06-12",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2023-06-28",
            "holiday_desc": "Eid'l Adha",
            "holiday_type": 3,
            "holiday_date2": "2023-06-28",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2023-08-02",
            "holiday_desc": "Adlaw Hong Butuan",
            "holiday_type": 3,
            "holiday_date2": "2023-08-02",
            "holiday_cover": 2,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2023-08-21",
            "holiday_desc": "Ninoy Aquino Day",
            "holiday_type": 3,
            "holiday_date2": "2023-08-21",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2023-08-28",
            "holiday_desc": "National Heroes Day",
            "holiday_type": 1,
            "holiday_date2": "2023-08-28",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2023-10-30",
            "holiday_desc": "BARANGAY AND SK ELECTION",
            "holiday_type": 3,
            "holiday_date2": "2023-10-30",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2023-11-01",
            "holiday_desc": "All Saints Day",
            "holiday_type": 3,
            "holiday_date2": "2023-11-01",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2023-11-02",
            "holiday_desc": "ALL SOULS' DAY",
            "holiday_type": 1,
            "holiday_date2": "2023-11-02",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2023-11-27",
            "holiday_desc": "BONIFACIO DAY",
            "holiday_type": 1,
            "holiday_date2": "2023-11-27",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2023-12-04",
            "holiday_desc": "EO# 29 S. 2023",
            "holiday_type": 6,
            "holiday_date2": "2023-12-04",
            "holiday_cover": 2,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2023-12-08",
            "holiday_desc": "FEAST OF THE IMMACULATE CONCEPTION OF MARY",
            "holiday_type": 3,
            "holiday_date2": "2023-12-08",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2023-12-25",
            "holiday_desc": "CHRISTMAS DAY",
            "holiday_type": 1,
            "holiday_date2": "2023-12-25",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2023-12-26",
            "holiday_desc": "PROCLAMATION NO.425",
            "holiday_type": 3,
            "holiday_date2": "2023-12-26",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2023-12-30",
            "holiday_desc": "Rizal Day",
            "holiday_type": 1,
            "holiday_date2": "2023-12-30",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2023-12-31",
            "holiday_desc": "New Year's Eve",
            "holiday_type": 3,
            "holiday_date2": "2023-12-31",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-01-01",
            "holiday_desc": "New Year",
            "holiday_type": 1,
            "holiday_date2": "2024-01-01",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-01-01",
            "holiday_desc": "New Year's Day",
            "holiday_type": 1,
            "holiday_date2": "2024-01-01",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-02-09",
            "holiday_desc": "Chinese New Year",
            "holiday_type": 3,
            "holiday_date2": "2024-02-09",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-02-24",
            "holiday_desc": "PROCLAMATION NO. 167 EDSA PEOPLE POWER",
            "holiday_type": 3,
            "holiday_date2": "2024-02-24",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-02-25",
            "holiday_desc": "People Power Day",
            "holiday_type": 3,
            "holiday_date2": "2024-02-25",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-02-25",
            "holiday_desc": "EDSA PEOPLE POWER ANNIVERSARY",
            "holiday_type": 3,
            "holiday_date2": "2024-02-25",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-03-28",
            "holiday_desc": "Holy Thursday",
            "holiday_type": 1,
            "holiday_date2": "2024-03-28",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-04-02",
            "holiday_desc": "Holy Good Friday",
            "holiday_type": 1,
            "holiday_date2": "2024-04-02",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-04-09",
            "holiday_desc": "Araw ng Kagitingan",
            "holiday_type": 1,
            "holiday_date2": "2024-04-09",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-04-14",
            "holiday_desc": "Holy Thursday",
            "holiday_type": 1,
            "holiday_date2": "2024-04-14",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-04-15",
            "holiday_desc": "Holy Black Saturday",
            "holiday_type": 1,
            "holiday_date2": "2024-04-15",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-04-17",
            "holiday_desc": "Holy Thursday",
            "holiday_type": 1,
            "holiday_date2": "2024-04-17",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-04-22",
            "holiday_desc": "Holy Good Friday",
            "holiday_type": 1,
            "holiday_date2": "2024-04-22",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-04-28",
            "holiday_desc": "ASEAN SUMMIT",
            "holiday_type": 3,
            "holiday_date2": "2024-04-28",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-05-01",
            "holiday_desc": "Labor Day",
            "holiday_type": 1,
            "holiday_date2": "2024-05-01",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-05-03",
            "holiday_desc": "Eid'l Fitr",
            "holiday_type": 3,
            "holiday_date2": "2024-05-03",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-05-09",
            "holiday_desc": "NATIONAL  AND LOCAL ELECTION",
            "holiday_type": 3,
            "holiday_date2": "2024-05-09",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-05-13",
            "holiday_desc": "Eid al-Fitr",
            "holiday_type": 1,
            "holiday_date2": "2024-05-13",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-05-19",
            "holiday_desc": "Balangay Festival",
            "holiday_type": 3,
            "holiday_date2": "2024-05-19",
            "holiday_cover": 2,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-06-12",
            "holiday_desc": "Philippine Independence Day",
            "holiday_type": 1,
            "holiday_date2": "2024-06-12",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-06-26",
            "holiday_desc": "Eid'l Fitr (End of Ramadan)",
            "holiday_type": 3,
            "holiday_date2": "2024-06-26",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-07-20",
            "holiday_desc": "Eid?l Adha",
            "holiday_type": 1,
            "holiday_date2": "2024-07-20",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-07-31",
            "holiday_desc": "EID AL-ADHA",
            "holiday_type": 3,
            "holiday_date2": "2024-07-31",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-08-02",
            "holiday_desc": "Adlaw Hong Butuan",
            "holiday_type": 3,
            "holiday_date2": "2024-08-02",
            "holiday_cover": 2,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-08-02",
            "holiday_desc": "Adlawhong Butuan",
            "holiday_type": 3,
            "holiday_date2": "2024-08-02",
            "holiday_cover": 2,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-08-07",
            "holiday_desc": "WORK SUSPENSION",
            "holiday_type": 5,
            "holiday_date2": "2024-08-07",
            "holiday_cover": 2,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-08-09",
            "holiday_desc": "Eidul-Fitar",
            "holiday_type": 1,
            "holiday_date2": "2024-08-09",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-08-20",
            "holiday_desc": "Work Suspended",
            "holiday_type": 5,
            "holiday_date2": "2024-08-20",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-08-21",
            "holiday_desc": "Ninoy Aquino Day",
            "holiday_type": 3,
            "holiday_date2": "2024-08-21",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-08-26",
            "holiday_desc": "National Heroes Day",
            "holiday_type": 1,
            "holiday_date2": "2024-08-26",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-08-31",
            "holiday_desc": "NATIONAL HEROES' DAY",
            "holiday_type": 3,
            "holiday_date2": "2024-08-31",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-09-12",
            "holiday_desc": "Valenzuela Charter Day",
            "holiday_type": 3,
            "holiday_date2": "2024-09-12",
            "holiday_cover": 2,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-09-12",
            "holiday_desc": "Eidi'l lAdha",
            "holiday_type": 1,
            "holiday_date2": "2024-09-12",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-10-15",
            "holiday_desc": "Eidul Adha",
            "holiday_type": 1,
            "holiday_date2": "2024-10-15",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-10-28",
            "holiday_desc": "Election Day",
            "holiday_type": 3,
            "holiday_date2": "2024-10-28",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-11-01",
            "holiday_desc": "All Saints Day",
            "holiday_type": 3,
            "holiday_date2": "2024-11-01",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-11-02",
            "holiday_desc": "Additional special non-working",
            "holiday_type": 3,
            "holiday_date2": "2024-11-02",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-11-02",
            "holiday_desc": "ALL SOULS' DAY",
            "holiday_type": 1,
            "holiday_date2": "2024-11-02",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-11-12",
            "holiday_desc": "Araw ng Valenzuela",
            "holiday_type": 3,
            "holiday_date2": "2024-11-12",
            "holiday_cover": 2,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-11-30",
            "holiday_desc": "Bonifacio Day",
            "holiday_type": 1,
            "holiday_date2": "2024-11-30",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-12-08",
            "holiday_desc": "FEAST OF THE IMMACULATE CONCEPTION OF MARY",
            "holiday_type": 3,
            "holiday_date2": "2024-12-08",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-12-24",
            "holiday_desc": "ADDITIONAL SPECIAL NON-WORKING DAY",
            "holiday_type": 3,
            "holiday_date2": "2024-12-24",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-12-24",
            "holiday_desc": "Christmas Eve",
            "holiday_type": 1,
            "holiday_date2": "2024-12-24",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-12-25",
            "holiday_desc": "Christmas Day",
            "holiday_type": 1,
            "holiday_date2": "2024-12-25",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-12-26",
            "holiday_desc": "Special non workng",
            "holiday_type": 3,
            "holiday_date2": "2024-12-26",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-12-30",
            "holiday_desc": "Rizal Day",
            "holiday_type": 1,
            "holiday_date2": "2024-12-30",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-12-31",
            "holiday_desc": "",
            "holiday_type": 4,
            "holiday_date2": "2024-12-31",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2024-12-31",
            "holiday_desc": "New Year's Eve",
            "holiday_type": 3,
            "holiday_date2": "2024-12-31",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-01-01",
            "holiday_desc": "New Year",
            "holiday_type": 1,
            "holiday_date2": "2025-01-01",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-01-01",
            "holiday_desc": "NEW YEAR'S DAY",
            "holiday_type": 1,
            "holiday_date2": "2025-01-01",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-01-02",
            "holiday_desc": "Special Non Working",
            "holiday_type": 3,
            "holiday_date2": "2025-01-02",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-01-31",
            "holiday_desc": "Chinese New Year",
            "holiday_type": 3,
            "holiday_date2": "2025-01-31",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-02-25",
            "holiday_desc": "EDSA PEOPLE POWER ANNIVERSARY",
            "holiday_type": 3,
            "holiday_date2": "2025-02-25",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-02-25",
            "holiday_desc": "People Power Day",
            "holiday_type": 3,
            "holiday_date2": "2025-02-25",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-04-09",
            "holiday_desc": "Araw ng Kagitingan",
            "holiday_type": 1,
            "holiday_date2": "2025-04-09",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-04-15",
            "holiday_desc": "Holy Black Saturday",
            "holiday_type": 1,
            "holiday_date2": "2025-04-15",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-04-17",
            "holiday_desc": "Holy Thursday",
            "holiday_type": 1,
            "holiday_date2": "2025-04-17",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-04-22",
            "holiday_desc": "Holy Good Friday",
            "holiday_type": 1,
            "holiday_date2": "2025-04-22",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-04-28",
            "holiday_desc": "ASEAN SUMMIT",
            "holiday_type": 3,
            "holiday_date2": "2025-04-28",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-05-01",
            "holiday_desc": "Labor Day",
            "holiday_type": 1,
            "holiday_date2": "2025-05-01",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-05-03",
            "holiday_desc": "Eid'l Fitr",
            "holiday_type": 3,
            "holiday_date2": "2025-05-03",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-05-09",
            "holiday_desc": "NATIONAL  AND LOCAL ELECTION",
            "holiday_type": 3,
            "holiday_date2": "2025-05-09",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-05-13",
            "holiday_desc": "Eid al-Fitr",
            "holiday_type": 1,
            "holiday_date2": "2025-05-13",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-05-19",
            "holiday_desc": "Balangay Festival",
            "holiday_type": 3,
            "holiday_date2": "2025-05-19",
            "holiday_cover": 2,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-06-12",
            "holiday_desc": "Philippine Independence Day",
            "holiday_type": 1,
            "holiday_date2": "2025-06-12",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-06-26",
            "holiday_desc": "Eid'l Fitr (End of Ramadan)",
            "holiday_type": 3,
            "holiday_date2": "2025-06-26",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-07-20",
            "holiday_desc": "Eid?l Adha",
            "holiday_type": 1,
            "holiday_date2": "2025-07-20",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-07-31",
            "holiday_desc": "EID AL-ADHA",
            "holiday_type": 3,
            "holiday_date2": "2025-07-31",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-08-02",
            "holiday_desc": "Adlaw Hong Butuan",
            "holiday_type": 3,
            "holiday_date2": "2025-08-02",
            "holiday_cover": 2,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-08-02",
            "holiday_desc": "Adlawhong Butuan",
            "holiday_type": 3,
            "holiday_date2": "2025-08-02",
            "holiday_cover": 2,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-08-07",
            "holiday_desc": "WORK SUSPENSION",
            "holiday_type": 5,
            "holiday_date2": "2025-08-07",
            "holiday_cover": 2,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-08-09",
            "holiday_desc": "Eidul-Fitar",
            "holiday_type": 1,
            "holiday_date2": "2025-08-09",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-08-20",
            "holiday_desc": "work suspended",
            "holiday_type": 5,
            "holiday_date2": "2025-08-20",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-08-21",
            "holiday_desc": "Ninoy Aquino Day",
            "holiday_type": 3,
            "holiday_date2": "2025-08-21",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-08-27",
            "holiday_desc": "National Heroes Day",
            "holiday_type": 1,
            "holiday_date2": "2025-08-27",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-08-31",
            "holiday_desc": "NATIONAL HEROES' DAY",
            "holiday_type": 3,
            "holiday_date2": "2025-08-31",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-09-12",
            "holiday_desc": "Eidi'l lAdha",
            "holiday_type": 1,
            "holiday_date2": "2025-09-12",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-09-12",
            "holiday_desc": "Valenzuela Charter Day",
            "holiday_type": 3,
            "holiday_date2": "2025-09-12",
            "holiday_cover": 2,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-10-15",
            "holiday_desc": "Eidul Adha",
            "holiday_type": 1,
            "holiday_date2": "2025-10-15",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-10-28",
            "holiday_desc": "Election Day",
            "holiday_type": 3,
            "holiday_date2": "2025-10-28",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-11-01",
            "holiday_desc": "All Saints Day",
            "holiday_type": 3,
            "holiday_date2": "2025-11-01",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-11-02",
            "holiday_desc": "Additional special non-working",
            "holiday_type": 3,
            "holiday_date2": "2025-11-02",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-11-02",
            "holiday_desc": "ALL SOULS' DAY",
            "holiday_type": 1,
            "holiday_date2": "2025-11-02",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-11-12",
            "holiday_desc": "Araw ng Valenzuela",
            "holiday_type": 3,
            "holiday_date2": "2025-11-12",
            "holiday_cover": 2,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-11-30",
            "holiday_desc": "Bonifacio Day",
            "holiday_type": 1,
            "holiday_date2": "2025-11-30",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-12-08",
            "holiday_desc": "FEAST OF THE IMMACULATE CONCEPTION OF MARY",
            "holiday_type": 3,
            "holiday_date2": "2025-12-08",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-12-24",
            "holiday_desc": "ADDITIONAL SPECIAL NON-WORKING DAY",
            "holiday_type": 3,
            "holiday_date2": "2025-12-24",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-12-24",
            "holiday_desc": "Christmas Eve",
            "holiday_type": 1,
            "holiday_date2": "2025-12-24",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-12-25",
            "holiday_desc": "Christmas Day",
            "holiday_type": 1,
            "holiday_date2": "2025-12-25",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-12-26",
            "holiday_desc": "Special non workng",
            "holiday_type": 3,
            "holiday_date2": "2025-12-26",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-12-30",
            "holiday_desc": "Rizal Day",
            "holiday_type": 1,
            "holiday_date2": "2025-12-30",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        },
        {
            "holiday_date1": "2025-12-31",
            "holiday_desc": "New Year's Eve",
            "holiday_type": 3,
            "holiday_date2": "2025-12-31",
            "holiday_cover": 1,
            "casual_pay": false,
            "contract_pay": false,
            "jo_pay": false,
            "regular_pay": false
        }
    ]
    }
    }
}
export function tempLogs(){
    return [
        {
        "emp_no": "16509",
        "bio_id": "13367",
        "work_date": "2023-12-01",
        "time_in": "      ",
        "half_break": "      ;      ",
        "time_out": "      ",
        "actual_in": "",
        "Actual_Break": ";",
        "Actual_Breakin": "",
        "adjust_break1": "",
        "adjust_break2": "",
        "actual_out": "",
        "sched_in": "08:00am",
        "sched_out": "05:00pm",
        "reg_hrs": "0.00",
        "absent_day": "1.00",
        "late_minutes": "0.00",
        "under_time": "0.00",
        "ot_minutes": "0.00",
        "leave_day": "1.00",
        "adjust_in": "",
        "adjust_out": "",
        "adjust_break_in": "",
        "adjust_break_out": "",
        "day_type": "0",
        "ob-ot-no": "0",
        "ob-ot-in": "",
        "ob-ot-out": "",
        "tran_type": "0",
        "remarks": ""
        },
        {
        "emp_no": "16509",
        "bio_id": "13367",
        "work_date": "2023-12-02",
        "time_in": "",
        "half_break": ";",
        "time_out": "",
        "actual_in": "",
        "Actual_Break": ";",
        "Actual_Breakin": "",
        "adjust_break1": "",
        "adjust_break2": "",
        "actual_out": "",
        "sched_in": "SATURDAY",
        "sched_out": "REST DAY",
        "reg_hrs": "0.00",
        "absent_day": "0.00",
        "late_minutes": "0.00",
        "under_time": "0.00",
        "ot_minutes": "0.00",
        "leave_day": "0.00",
        "adjust_in": "",
        "adjust_out": "",
        "adjust_break_in": "",
        "adjust_break_out": "",
        "day_type": "1",
        "ob-ot-no": "0",
        "ob-ot-in": "",
        "ob-ot-out": "",
        "tran_type": "0",
        "remarks": ""
        },
        {
        "emp_no": "16509",
        "bio_id": "13367",
        "work_date": "2023-12-03",
        "time_in": "",
        "half_break": ";",
        "time_out": "",
        "actual_in": "",
        "Actual_Break": ";",
        "Actual_Breakin": "",
        "adjust_break1": "",
        "adjust_break2": "",
        "actual_out": "",
        "sched_in": "SUNDAY",
        "sched_out": "REST DAY",
        "reg_hrs": "0.00",
        "absent_day": "0.00",
        "late_minutes": "0.00",
        "under_time": "0.00",
        "ot_minutes": "0.00",
        "leave_day": "0.00",
        "adjust_in": "",
        "adjust_out": "",
        "adjust_break_in": "",
        "adjust_break_out": "",
        "day_type": "1",
        "ob-ot-no": "0",
        "ob-ot-in": "",
        "ob-ot-out": "",
        "tran_type": "0",
        "remarks": ""
        },
        {
        "emp_no": "16509",
        "bio_id": "13367",
        "work_date": "2023-12-04",
        "time_in": "",
        "half_break": ";SL W/Pay",
        "time_out": "",
        "actual_in": "",
        "Actual_Break": ";",
        "Actual_Breakin": "",
        "adjust_break1": "",
        "adjust_break2": "",
        "actual_out": "",
        "sched_in": "HALF-DAY",
        "sched_out": "05:00pm",
        "reg_hrs": "0.00",
        "absent_day": "0.00",
        "late_minutes": "0.00",
        "under_time": "0.00",
        "ot_minutes": "0.00",
        "leave_day": "1.00",
        "adjust_in": "",
        "adjust_out": "",
        "adjust_break_in": "",
        "adjust_break_out": "",
        "day_type": "0",
        "ob-ot-no": "0",
        "ob-ot-in": "",
        "ob-ot-out": "",
        "tran_type": "9",
        "remarks": ""
        },
        {
        "emp_no": "16509",
        "bio_id": "13367",
        "work_date": "2023-12-05",
        "time_in": "      ",
        "half_break": "      ;      ",
        "time_out": "      ",
        "actual_in": "",
        "Actual_Break": ";",
        "Actual_Breakin": "",
        "adjust_break1": "",
        "adjust_break2": "",
        "actual_out": "",
        "sched_in": "08:00am",
        "sched_out": "05:00pm",
        "reg_hrs": "0.00",
        "absent_day": "1.00",
        "late_minutes": "0.00",
        "under_time": "0.00",
        "ot_minutes": "0.00",
        "leave_day": "1.00",
        "adjust_in": "",
        "adjust_out": "",
        "adjust_break_in": "",
        "adjust_break_out": "",
        "day_type": "0",
        "ob-ot-no": "0",
        "ob-ot-in": "",
        "ob-ot-out": "",
        "tran_type": "0",
        "remarks": ""
        },
        {
        "emp_no": "16509",
        "bio_id": "13367",
        "work_date": "2023-12-06",
        "time_in": "      ",
        "half_break": "      ;      ",
        "time_out": "      ",
        "actual_in": "",
        "Actual_Break": ";",
        "Actual_Breakin": "",
        "adjust_break1": "",
        "adjust_break2": "",
        "actual_out": "",
        "sched_in": "08:00am",
        "sched_out": "05:00pm",
        "reg_hrs": "0.00",
        "absent_day": "1.00",
        "late_minutes": "0.00",
        "under_time": "0.00",
        "ot_minutes": "0.00",
        "leave_day": "1.00",
        "adjust_in": "",
        "adjust_out": "",
        "adjust_break_in": "",
        "adjust_break_out": "",
        "day_type": "0",
        "ob-ot-no": "0",
        "ob-ot-in": "",
        "ob-ot-out": "",
        "tran_type": "0",
        "remarks": ""
        },
        {
        "emp_no": "16509",
        "bio_id": "13367",
        "work_date": "2023-12-07",
        "time_in": "      ",
        "half_break": "      ;      ",
        "time_out": "      ",
        "actual_in": "",
        "Actual_Break": ";",
        "Actual_Breakin": "",
        "adjust_break1": "",
        "adjust_break2": "",
        "actual_out": "",
        "sched_in": "08:00am",
        "sched_out": "05:00pm",
        "reg_hrs": "0.00",
        "absent_day": "1.00",
        "late_minutes": "0.00",
        "under_time": "0.00",
        "ot_minutes": "0.00",
        "leave_day": "1.00",
        "adjust_in": "",
        "adjust_out": "",
        "adjust_break_in": "",
        "adjust_break_out": "",
        "day_type": "0",
        "ob-ot-no": "0",
        "ob-ot-in": "",
        "ob-ot-out": "",
        "tran_type": "0",
        "remarks": ""
        },
        {
        "emp_no": "16509",
        "bio_id": "13367",
        "work_date": "2023-12-08",
        "time_in": "",
        "half_break": ";",
        "time_out": "",
        "actual_in": "",
        "Actual_Break": ";",
        "Actual_Breakin": "",
        "adjust_break1": "",
        "adjust_break2": "",
        "actual_out": "",
        "sched_in": "NATIONAL",
        "sched_out": "HOLIDAY",
        "reg_hrs": "0.00",
        "absent_day": "0.00",
        "late_minutes": "0.00",
        "under_time": "0.00",
        "ot_minutes": "0.00",
        "leave_day": "1.00",
        "adjust_in": "",
        "adjust_out": "",
        "adjust_break_in": "",
        "adjust_break_out": "",
        "day_type": "3",
        "ob-ot-no": "0",
        "ob-ot-in": "",
        "ob-ot-out": "",
        "tran_type": "6",
        "remarks": ""
        },
        {
        "emp_no": "16509",
        "bio_id": "13367",
        "work_date": "2023-12-09",
        "time_in": "",
        "half_break": ";",
        "time_out": "",
        "actual_in": "",
        "Actual_Break": ";",
        "Actual_Breakin": "",
        "adjust_break1": "",
        "adjust_break2": "",
        "actual_out": "",
        "sched_in": "SATURDAY",
        "sched_out": "REST DAY",
        "reg_hrs": "0.00",
        "absent_day": "0.00",
        "late_minutes": "0.00",
        "under_time": "0.00",
        "ot_minutes": "0.00",
        "leave_day": "0.00",
        "adjust_in": "",
        "adjust_out": "",
        "adjust_break_in": "",
        "adjust_break_out": "",
        "day_type": "1",
        "ob-ot-no": "0",
        "ob-ot-in": "",
        "ob-ot-out": "",
        "tran_type": "0",
        "remarks": ""
        },
        {
        "emp_no": "16509",
        "bio_id": "13367",
        "work_date": "2023-12-10",
        "time_in": "",
        "half_break": ";",
        "time_out": "",
        "actual_in": "",
        "Actual_Break": ";",
        "Actual_Breakin": "",
        "adjust_break1": "",
        "adjust_break2": "",
        "actual_out": "",
        "sched_in": "SUNDAY",
        "sched_out": "REST DAY",
        "reg_hrs": "0.00",
        "absent_day": "0.00",
        "late_minutes": "0.00",
        "under_time": "0.00",
        "ot_minutes": "0.00",
        "leave_day": "0.00",
        "adjust_in": "",
        "adjust_out": "",
        "adjust_break_in": "",
        "adjust_break_out": "",
        "day_type": "1",
        "ob-ot-no": "0",
        "ob-ot-in": "",
        "ob-ot-out": "",
        "tran_type": "0",
        "remarks": ""
        },
        {
        "emp_no": "16509",
        "bio_id": "13367",
        "work_date": "2023-12-11",
        "time_in": "      ",
        "half_break": "      ;      ",
        "time_out": "      ",
        "actual_in": "",
        "Actual_Break": ";",
        "Actual_Breakin": "",
        "adjust_break1": "",
        "adjust_break2": "",
        "actual_out": "",
        "sched_in": "08:00am",
        "sched_out": "05:00pm",
        "reg_hrs": "0.00",
        "absent_day": "1.00",
        "late_minutes": "0.00",
        "under_time": "0.00",
        "ot_minutes": "0.00",
        "leave_day": "1.00",
        "adjust_in": "",
        "adjust_out": "",
        "adjust_break_in": "",
        "adjust_break_out": "",
        "day_type": "0",
        "ob-ot-no": "0",
        "ob-ot-in": "",
        "ob-ot-out": "",
        "tran_type": "0",
        "remarks": ""
        },
        {
        "emp_no": "16509",
        "bio_id": "13367",
        "work_date": "2023-12-12",
        "time_in": "      ",
        "half_break": "      ;      ",
        "time_out": "      ",
        "actual_in": "",
        "Actual_Break": ";",
        "Actual_Breakin": "",
        "adjust_break1": "",
        "adjust_break2": "",
        "actual_out": "",
        "sched_in": "08:00am",
        "sched_out": "05:00pm",
        "reg_hrs": "0.00",
        "absent_day": "1.00",
        "late_minutes": "0.00",
        "under_time": "0.00",
        "ot_minutes": "0.00",
        "leave_day": "1.00",
        "adjust_in": "",
        "adjust_out": "",
        "adjust_break_in": "",
        "adjust_break_out": "",
        "day_type": "0",
        "ob-ot-no": "0",
        "ob-ot-in": "",
        "ob-ot-out": "",
        "tran_type": "0",
        "remarks": ""
        },
        {
        "emp_no": "16509",
        "bio_id": "13367",
        "work_date": "2023-12-13",
        "time_in": "      ",
        "half_break": "      ;      ",
        "time_out": "      ",
        "actual_in": "",
        "Actual_Break": ";",
        "Actual_Breakin": "",
        "adjust_break1": "",
        "adjust_break2": "",
        "actual_out": "",
        "sched_in": "08:00am",
        "sched_out": "05:00pm",
        "reg_hrs": "0.00",
        "absent_day": "1.00",
        "late_minutes": "0.00",
        "under_time": "0.00",
        "ot_minutes": "0.00",
        "leave_day": "1.00",
        "adjust_in": "",
        "adjust_out": "",
        "adjust_break_in": "",
        "adjust_break_out": "",
        "day_type": "0",
        "ob-ot-no": "0",
        "ob-ot-in": "",
        "ob-ot-out": "",
        "tran_type": "0",
        "remarks": ""
        },
        {
        "emp_no": "16509",
        "bio_id": "13367",
        "work_date": "2023-12-14",
        "time_in": "      ",
        "half_break": "      ;      ",
        "time_out": "      ",
        "actual_in": "",
        "Actual_Break": ";",
        "Actual_Breakin": "",
        "adjust_break1": "",
        "adjust_break2": "",
        "actual_out": "",
        "sched_in": "08:00am",
        "sched_out": "05:00pm",
        "reg_hrs": "0.00",
        "absent_day": "1.00",
        "late_minutes": "0.00",
        "under_time": "0.00",
        "ot_minutes": "0.00",
        "leave_day": "1.00",
        "adjust_in": "",
        "adjust_out": "",
        "adjust_break_in": "",
        "adjust_break_out": "",
        "day_type": "0",
        "ob-ot-no": "0",
        "ob-ot-in": "",
        "ob-ot-out": "",
        "tran_type": "0",
        "remarks": ""
        },
        {
        "emp_no": "16509",
        "bio_id": "13367",
        "work_date": "2023-12-15",
        "time_in": "      ",
        "half_break": "      ;      ",
        "time_out": "      ",
        "actual_in": "",
        "Actual_Break": ";",
        "Actual_Breakin": "",
        "adjust_break1": "",
        "adjust_break2": "",
        "actual_out": "",
        "sched_in": "08:00am",
        "sched_out": "05:00pm",
        "reg_hrs": "0.00",
        "absent_day": "1.00",
        "late_minutes": "0.00",
        "under_time": "0.00",
        "ot_minutes": "0.00",
        "leave_day": "1.00",
        "adjust_in": "",
        "adjust_out": "",
        "adjust_break_in": "",
        "adjust_break_out": "",
        "day_type": "0",
        "ob-ot-no": "0",
        "ob-ot-in": "",
        "ob-ot-out": "",
        "tran_type": "0",
        "remarks": ""
        },
        {
        "emp_no": "16509",
        "bio_id": "13367",
        "work_date": "2023-12-16",
        "time_in": "",
        "half_break": ";",
        "time_out": "",
        "actual_in": "",
        "Actual_Break": ";",
        "Actual_Breakin": "",
        "adjust_break1": "",
        "adjust_break2": "",
        "actual_out": "",
        "sched_in": "SATURDAY",
        "sched_out": "REST DAY",
        "reg_hrs": "0.00",
        "absent_day": "0.00",
        "late_minutes": "0.00",
        "under_time": "0.00",
        "ot_minutes": "0.00",
        "leave_day": "0.00",
        "adjust_in": "",
        "adjust_out": "",
        "adjust_break_in": "",
        "adjust_break_out": "",
        "day_type": "1",
        "ob-ot-no": "0",
        "ob-ot-in": "",
        "ob-ot-out": "",
        "tran_type": "0",
        "remarks": ""
        },
        {
        "emp_no": "16509",
        "bio_id": "13367",
        "work_date": "2023-12-17",
        "time_in": "",
        "half_break": ";",
        "time_out": "",
        "actual_in": "",
        "Actual_Break": ";",
        "Actual_Breakin": "",
        "adjust_break1": "",
        "adjust_break2": "",
        "actual_out": "",
        "sched_in": "SUNDAY",
        "sched_out": "REST DAY",
        "reg_hrs": "0.00",
        "absent_day": "0.00",
        "late_minutes": "0.00",
        "under_time": "0.00",
        "ot_minutes": "0.00",
        "leave_day": "0.00",
        "adjust_in": "",
        "adjust_out": "",
        "adjust_break_in": "",
        "adjust_break_out": "",
        "day_type": "1",
        "ob-ot-no": "0",
        "ob-ot-in": "",
        "ob-ot-out": "",
        "tran_type": "0",
        "remarks": ""
        },
        {
        "emp_no": "16509",
        "bio_id": "13367",
        "work_date": "2023-12-18",
        "time_in": "      ",
        "half_break": "      ;      ",
        "time_out": "      ",
        "actual_in": "",
        "Actual_Break": ";",
        "Actual_Breakin": "",
        "adjust_break1": "",
        "adjust_break2": "",
        "actual_out": "",
        "sched_in": "08:00am",
        "sched_out": "05:00pm",
        "reg_hrs": "0.00",
        "absent_day": "1.00",
        "late_minutes": "0.00",
        "under_time": "0.00",
        "ot_minutes": "0.00",
        "leave_day": "1.00",
        "adjust_in": "",
        "adjust_out": "",
        "adjust_break_in": "",
        "adjust_break_out": "",
        "day_type": "0",
        "ob-ot-no": "0",
        "ob-ot-in": "",
        "ob-ot-out": "",
        "tran_type": "0",
        "remarks": ""
        },
        {
        "emp_no": "16509",
        "bio_id": "13367",
        "work_date": "2023-12-19",
        "time_in": "      ",
        "half_break": "      ;      ",
        "time_out": "      ",
        "actual_in": "",
        "Actual_Break": ";",
        "Actual_Breakin": "",
        "adjust_break1": "",
        "adjust_break2": "",
        "actual_out": "",
        "sched_in": "08:00am",
        "sched_out": "05:00pm",
        "reg_hrs": "0.00",
        "absent_day": "1.00",
        "late_minutes": "0.00",
        "under_time": "0.00",
        "ot_minutes": "0.00",
        "leave_day": "1.00",
        "adjust_in": "",
        "adjust_out": "",
        "adjust_break_in": "",
        "adjust_break_out": "",
        "day_type": "0",
        "ob-ot-no": "0",
        "ob-ot-in": "",
        "ob-ot-out": "",
        "tran_type": "0",
        "remarks": ""
        },
        {
        "emp_no": "16509",
        "bio_id": "13367",
        "work_date": "2023-12-20",
        "time_in": "      ",
        "half_break": "      ;      ",
        "time_out": "      ",
        "actual_in": "",
        "Actual_Break": ";",
        "Actual_Breakin": "",
        "adjust_break1": "",
        "adjust_break2": "",
        "actual_out": "",
        "sched_in": "08:00am",
        "sched_out": "05:00pm",
        "reg_hrs": "0.00",
        "absent_day": "1.00",
        "late_minutes": "0.00",
        "under_time": "0.00",
        "ot_minutes": "0.00",
        "leave_day": "1.00",
        "adjust_in": "",
        "adjust_out": "",
        "adjust_break_in": "",
        "adjust_break_out": "",
        "day_type": "0",
        "ob-ot-no": "0",
        "ob-ot-in": "",
        "ob-ot-out": "",
        "tran_type": "0",
        "remarks": ""
        },
        {
        "emp_no": "16509",
        "bio_id": "13367",
        "work_date": "2023-12-21",
        "time_in": "      ",
        "half_break": "      ;      ",
        "time_out": "      ",
        "actual_in": "",
        "Actual_Break": ";",
        "Actual_Breakin": "",
        "adjust_break1": "",
        "adjust_break2": "",
        "actual_out": "",
        "sched_in": "08:00am",
        "sched_out": "05:00pm",
        "reg_hrs": "0.00",
        "absent_day": "1.00",
        "late_minutes": "0.00",
        "under_time": "0.00",
        "ot_minutes": "0.00",
        "leave_day": "1.00",
        "adjust_in": "",
        "adjust_out": "",
        "adjust_break_in": "",
        "adjust_break_out": "",
        "day_type": "0",
        "ob-ot-no": "0",
        "ob-ot-in": "",
        "ob-ot-out": "",
        "tran_type": "0",
        "remarks": ""
        },
        {
        "emp_no": "16509",
        "bio_id": "13367",
        "work_date": "2023-12-22",
        "time_in": "      ",
        "half_break": "      ;      ",
        "time_out": "      ",
        "actual_in": "",
        "Actual_Break": ";",
        "Actual_Breakin": "",
        "adjust_break1": "",
        "adjust_break2": "",
        "actual_out": "",
        "sched_in": "08:00am",
        "sched_out": "05:00pm",
        "reg_hrs": "0.00",
        "absent_day": "1.00",
        "late_minutes": "0.00",
        "under_time": "0.00",
        "ot_minutes": "0.00",
        "leave_day": "1.00",
        "adjust_in": "",
        "adjust_out": "",
        "adjust_break_in": "",
        "adjust_break_out": "",
        "day_type": "0",
        "ob-ot-no": "0",
        "ob-ot-in": "",
        "ob-ot-out": "",
        "tran_type": "0",
        "remarks": ""
        },
        {
        "emp_no": "16509",
        "bio_id": "13367",
        "work_date": "2023-12-23",
        "time_in": "",
        "half_break": ";",
        "time_out": "",
        "actual_in": "",
        "Actual_Break": ";",
        "Actual_Breakin": "",
        "adjust_break1": "",
        "adjust_break2": "",
        "actual_out": "",
        "sched_in": "SATURDAY",
        "sched_out": "REST DAY",
        "reg_hrs": "0.00",
        "absent_day": "0.00",
        "late_minutes": "0.00",
        "under_time": "0.00",
        "ot_minutes": "0.00",
        "leave_day": "0.00",
        "adjust_in": "",
        "adjust_out": "",
        "adjust_break_in": "",
        "adjust_break_out": "",
        "day_type": "1",
        "ob-ot-no": "0",
        "ob-ot-in": "",
        "ob-ot-out": "",
        "tran_type": "0",
        "remarks": ""
        },
        {
        "emp_no": "16509",
        "bio_id": "13367",
        "work_date": "2023-12-24",
        "time_in": "",
        "half_break": ";",
        "time_out": "",
        "actual_in": "",
        "Actual_Break": ";",
        "Actual_Breakin": "",
        "adjust_break1": "",
        "adjust_break2": "",
        "actual_out": "",
        "sched_in": "SUNDAY",
        "sched_out": "REST DAY",
        "reg_hrs": "0.00",
        "absent_day": "0.00",
        "late_minutes": "0.00",
        "under_time": "0.00",
        "ot_minutes": "0.00",
        "leave_day": "0.00",
        "adjust_in": "",
        "adjust_out": "",
        "adjust_break_in": "",
        "adjust_break_out": "",
        "day_type": "1",
        "ob-ot-no": "0",
        "ob-ot-in": "",
        "ob-ot-out": "",
        "tran_type": "0",
        "remarks": ""
        },
        {
        "emp_no": "16509",
        "bio_id": "13367",
        "work_date": "2023-12-25",
        "time_in": "",
        "half_break": ";",
        "time_out": "",
        "actual_in": "",
        "Actual_Break": ";",
        "Actual_Breakin": "",
        "adjust_break1": "",
        "adjust_break2": "",
        "actual_out": "",
        "sched_in": "NATIONAL",
        "sched_out": "HOLIDAY",
        "reg_hrs": "0.00",
        "absent_day": "0.00",
        "late_minutes": "0.00",
        "under_time": "0.00",
        "ot_minutes": "0.00",
        "leave_day": "1.00",
        "adjust_in": "",
        "adjust_out": "",
        "adjust_break_in": "",
        "adjust_break_out": "",
        "day_type": "2",
        "ob-ot-no": "0",
        "ob-ot-in": "",
        "ob-ot-out": "",
        "tran_type": "6",
        "remarks": ""
        },
        {
        "emp_no": "16509",
        "bio_id": "13367",
        "work_date": "2023-12-26",
        "time_in": "08:01am",
        "half_break": "12:01pm;12:02pm",
        "time_out": "06:01pm",
        "actual_in": "08:01:32",
        "Actual_Break": "12:01:32;12:02:32",
        "Actual_Breakin": "",
        "adjust_break1": "",
        "adjust_break2": "",
        "actual_out": "18:01:32",
        "sched_in": "08:00am",
        "sched_out": "05:00pm",
        "reg_hrs": "0.00",
        "absent_day": "0.00",
        "late_minutes": "0.00",
        "under_time": "0.00",
        "ot_minutes": "0.00",
        "leave_day": "0.00",
        "adjust_in": "",
        "adjust_out": "",
        "adjust_break_in": "",
        "adjust_break_out": "",
        "day_type": "3",
        "ob-ot-no": "0",
        "ob-ot-in": "",
        "ob-ot-out": "",
        "tran_type": "6",
        "remarks": ""
        },
        {
        "emp_no": "16509",
        "bio_id": "13367",
        "work_date": "2023-12-27",
        "time_in": "      ",
        "half_break": "      ;      ",
        "time_out": "      ",
        "actual_in": "",
        "Actual_Break": ";",
        "Actual_Breakin": "",
        "adjust_break1": "",
        "adjust_break2": "",
        "actual_out": "",
        "sched_in": "08:00am",
        "sched_out": "05:00pm",
        "reg_hrs": "0.00",
        "absent_day": "1.00",
        "late_minutes": "0.00",
        "under_time": "0.00",
        "ot_minutes": "0.00",
        "leave_day": "1.00",
        "adjust_in": "",
        "adjust_out": "",
        "adjust_break_in": "",
        "adjust_break_out": "",
        "day_type": "0",
        "ob-ot-no": "0",
        "ob-ot-in": "",
        "ob-ot-out": "",
        "tran_type": "0",
        "remarks": ""
        },
        {
        "emp_no": "16509",
        "bio_id": "13367",
        "work_date": "2023-12-28",
        "time_in": "      ",
        "half_break": "      ;      ",
        "time_out": "      ",
        "actual_in": "",
        "Actual_Break": ";",
        "Actual_Breakin": "",
        "adjust_break1": "",
        "adjust_break2": "",
        "actual_out": "",
        "sched_in": "08:00am",
        "sched_out": "05:00pm",
        "reg_hrs": "0.00",
        "absent_day": "1.00",
        "late_minutes": "0.00",
        "under_time": "0.00",
        "ot_minutes": "0.00",
        "leave_day": "1.00",
        "adjust_in": "",
        "adjust_out": "",
        "adjust_break_in": "",
        "adjust_break_out": "",
        "day_type": "0",
        "ob-ot-no": "0",
        "ob-ot-in": "",
        "ob-ot-out": "",
        "tran_type": "0",
        "remarks": ""
        },
        {
        "emp_no": "16509",
        "bio_id": "13367",
        "work_date": "2023-12-29",
        "time_in": "      ",
        "half_break": "      ;      ",
        "time_out": "      ",
        "actual_in": "",
        "Actual_Break": ";",
        "Actual_Breakin": "",
        "adjust_break1": "",
        "adjust_break2": "",
        "actual_out": "",
        "sched_in": "08:00am",
        "sched_out": "05:00pm",
        "reg_hrs": "0.00",
        "absent_day": "1.00",
        "late_minutes": "0.00",
        "under_time": "0.00",
        "ot_minutes": "0.00",
        "leave_day": "1.00",
        "adjust_in": "",
        "adjust_out": "",
        "adjust_break_in": "",
        "adjust_break_out": "",
        "day_type": "0",
        "ob-ot-no": "0",
        "ob-ot-in": "",
        "ob-ot-out": "",
        "tran_type": "0",
        "remarks": ""
        },
        {
        "emp_no": "16509",
        "bio_id": "13367",
        "work_date": "2023-12-30",
        "time_in": "",
        "half_break": ";",
        "time_out": "",
        "actual_in": "",
        "Actual_Break": ";",
        "Actual_Breakin": "",
        "adjust_break1": "",
        "adjust_break2": "",
        "actual_out": "",
        "sched_in": "SATURDAY",
        "sched_out": "REST DAY",
        "reg_hrs": "0.00",
        "absent_day": "0.00",
        "late_minutes": "0.00",
        "under_time": "0.00",
        "ot_minutes": "0.00",
        "leave_day": "0.00",
        "adjust_in": "",
        "adjust_out": "",
        "adjust_break_in": "",
        "adjust_break_out": "",
        "day_type": "1",
        "ob-ot-no": "0",
        "ob-ot-in": "",
        "ob-ot-out": "",
        "tran_type": "0",
        "remarks": ""
        },
        {
        "emp_no": "16509",
        "bio_id": "13367",
        "work_date": "2023-12-31",
        "time_in": "",
        "half_break": ";",
        "time_out": "",
        "actual_in": "",
        "Actual_Break": ";",
        "Actual_Breakin": "",
        "adjust_break1": "",
        "adjust_break2": "",
        "actual_out": "",
        "sched_in": "SUNDAY",
        "sched_out": "REST DAY",
        "reg_hrs": "0.00",
        "absent_day": "0.00",
        "late_minutes": "0.00",
        "under_time": "0.00",
        "ot_minutes": "0.00",
        "leave_day": "0.00",
        "adjust_in": "",
        "adjust_out": "",
        "adjust_break_in": "",
        "adjust_break_out": "",
        "day_type": "1",
        "ob-ot-no": "0",
        "ob-ot-in": "",
        "ob-ot-out": "",
        "tran_type": "0",
        "remarks": ""
        }
        ]
}