export const fakeApplicant = [
  {
    id: 21,
    prf_id: 79,
    remark: "SELECTED",
    is_employee: 0,
    app_id: 11840,
    is_hired: null,
    appoint_date: '["2024-11-16","2024-12-31"]',
    fname: "DEONY",
    id_no: null,
    mname: "POMAR",
    lname: "CULENTAS",
    extname: "N/A",
    emailadd: "deonyculentas@gmail.com",
    telno: "NONE",
    cpno: "09639592482",
    office_dept: "CITY BUDGET DEPARTMENT",
    div_name: "Office of the Department Head",
    sec_name: "N/A",
    unit_name: "N/A",
    position_title: "Administrative Officer II (Clearing Officer)",
    created_at: "2024-09-25",
    positiontitle: "FARM WORKER",
    agency: "CITY AGRICULTURE OFFICE",
    elevel: "ELEMENTARY",
    nschool: "Talacogon Elementary School",
    degreecourse: "PRIMARY EDUCATION",
    title: null,
    rating: null,
    licenseno: null,
  },
  {
    id: 21,
    prf_id: 79,
    remark: "SELECTED",
    is_employee: 0,
    app_id: 11840,
    is_hired: null,
    appoint_date: '["2024-11-16","2024-12-31"]',
    fname: "DEONY",
    id_no: null,
    mname: "POMAR",
    lname: "CULENTAS",
    extname: "N/A",
    emailadd: "deonyculentas@gmail.com",
    telno: "NONE",
    cpno: "09639592482",
    office_dept: "CITY BUDGET DEPARTMENT",
    div_name: "Office of the Department Head",
    sec_name: "N/A",
    unit_name: "N/A",
    position_title: "Administrative Officer II (Clearing Officer)",
    created_at: "2024-09-25",
    positiontitle: "FARM WORKER",
    agency: "CITY AGRICULTURE OFFICE",
    elevel: "ELEMENTARY",
    nschool: "Talacogon Elementary School",
    degreecourse: "PRIMARY EDUCATION",
    title: null,
    rating: null,
    licenseno: null,
  },
  {
    id: 21,
    prf_id: 79,
    remark: "SELECTED",
    is_employee: 0,
    app_id: 11840,
    is_hired: null,
    appoint_date: '["2024-11-16","2024-12-31"]',
    fname: "DEONY",
    id_no: null,
    mname: "POMAR",
    lname: "CULENTAS",
    extname: "N/A",
    emailadd: "deonyculentas@gmail.com",
    telno: "NONE",
    cpno: "09639592482",
    office_dept: "CITY BUDGET DEPARTMENT",
    div_name: "Office of the Department Head",
    sec_name: "N/A",
    unit_name: "N/A",
    position_title: "Administrative Officer II (Clearing Officer)",
    created_at: "2024-09-25",
    positiontitle: "FARM WORKER",
    agency: "CITY AGRICULTURE OFFICE",
    elevel: "ELEMENTARY",
    nschool: "Talacogon Elementary School",
    degreecourse: "PRIMARY EDUCATION",
    title: null,
    rating: null,
    licenseno: null,
  },
  {
    id: 21,
    prf_id: 79,
    remark: "SELECTED",
    is_employee: 0,
    app_id: 11840,
    is_hired: null,
    appoint_date: '["2024-11-16","2024-12-31"]',
    fname: "DEONY",
    id_no: null,
    mname: "POMAR",
    lname: "CULENTAS",
    extname: "N/A",
    emailadd: "deonyculentas@gmail.com",
    telno: "NONE",
    cpno: "09639592482",
    office_dept: "CITY BUDGET DEPARTMENT",
    div_name: "Office of the Department Head",
    sec_name: "N/A",
    unit_name: "N/A",
    position_title: "Administrative Officer II (Clearing Officer)",
    created_at: "2024-09-25",
    positiontitle: "FARM WORKER",
    agency: "CITY AGRICULTURE OFFICE",
    elevel: "ELEMENTARY",
    nschool: "Talacogon Elementary School",
    degreecourse: "PRIMARY EDUCATION",
    title: null,
    rating: null,
    licenseno: null,
  },
  {
    id: 21,
    prf_id: 79,
    remark: "SELECTED",
    is_employee: 0,
    app_id: 11840,
    is_hired: null,
    appoint_date: '["2024-11-16","2024-12-31"]',
    fname: "DEONY",
    id_no: null,
    mname: "POMAR",
    lname: "CULENTAS",
    extname: "N/A",
    emailadd: "deonyculentas@gmail.com",
    telno: "NONE",
    cpno: "09639592482",
    office_dept: "CITY BUDGET DEPARTMENT",
    div_name: "Office of the Department Head",
    sec_name: "N/A",
    unit_name: "N/A",
    position_title: "Administrative Officer II (Clearing Officer)",
    created_at: "2024-09-25",
    positiontitle: "FARM WORKER",
    agency: "CITY AGRICULTURE OFFICE",
    elevel: "ELEMENTARY",
    nschool: "Talacogon Elementary School",
    degreecourse: "PRIMARY EDUCATION",
    title: null,
    rating: null,
    licenseno: null,
  },
  {
    id: 21,
    prf_id: 79,
    remark: "SELECTED",
    is_employee: 0,
    app_id: 11840,
    is_hired: null,
    appoint_date: '["2024-11-16","2024-12-31"]',
    fname: "DEONY",
    id_no: null,
    mname: "POMAR",
    lname: "CULENTAS",
    extname: "N/A",
    emailadd: "deonyculentas@gmail.com",
    telno: "NONE",
    cpno: "09639592482",
    office_dept: "CITY BUDGET DEPARTMENT",
    div_name: "Office of the Department Head",
    sec_name: "N/A",
    unit_name: "N/A",
    position_title: "Administrative Officer II (Clearing Officer)",
    created_at: "2024-09-25",
    positiontitle: "FARM WORKER",
    agency: "CITY AGRICULTURE OFFICE",
    elevel: "ELEMENTARY",
    nschool: "Talacogon Elementary School",
    degreecourse: "PRIMARY EDUCATION",
    title: null,
    rating: null,
    licenseno: null,
  },
  {
    id: 21,
    prf_id: 79,
    remark: "SELECTED",
    is_employee: 0,
    app_id: 11840,
    is_hired: null,
    appoint_date: '["2024-11-16","2024-12-31"]',
    fname: "DEONY",
    id_no: null,
    mname: "POMAR",
    lname: "CULENTAS",
    extname: "N/A",
    emailadd: "deonyculentas@gmail.com",
    telno: "NONE",
    cpno: "09639592482",
    office_dept: "CITY BUDGET DEPARTMENT",
    div_name: "Office of the Department Head",
    sec_name: "N/A",
    unit_name: "N/A",
    position_title: "Administrative Officer II (Clearing Officer)",
    created_at: "2024-09-25",
    positiontitle: "FARM WORKER",
    agency: "CITY AGRICULTURE OFFICE",
    elevel: "ELEMENTARY",
    nschool: "Talacogon Elementary School",
    degreecourse: "PRIMARY EDUCATION",
    title: null,
    rating: null,
    licenseno: null,
  },
];
